language: python
sudo: required
install: true
before_install:
 - chmod +x runsqa.sh
env:
 - SONAR_HOST_URL=https://nemo.sonarqube.org
language: java
jdk:
  - oraclejdk7
  - openjdk6
script:
 - ./runsqa.sh
