language: java
jdk:
  - oraclejdk8
sudo: required
install: true
before_install:
 - chmod +x runsqa.sh
 - sudo apt-get update
env:
 - SONAR_HOST_URL="https://nemo.sonarqube.org/"
script:
 - ./runsqa.sh
