language: python
sudo: required
install: true
before_install:
 - chmod +x runsqa.sh
 - apt-get install oracle-java9-installer
env:
 - SONAR_HOST_URL=https://nemo.sonarqube.org
language: java

script:
 - ./runsqa.sh
